//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.20 at 08:50:38 nachm. MESZ 
//


package de.htwg.gib.egkterminal.model.medikationsplan.dosiereinheit;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.htwg.gib.egkterminal.model.medikationsplan.dosiereinheit package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.htwg.gib.egkterminal.model.medikationsplan.dosiereinheit
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Dosiereinheiten.Schluesseltabelle }
     * 
     */
    public Dosiereinheiten.Schluesseltabelle createDosiereinheitenSchluesseltabelle() {
        return new Dosiereinheiten.Schluesseltabelle();
    }

    /**
     * Create an instance of {@link Dosiereinheiten.Schluesseltabelle.Dosiereinheit }
     * 
     */
    public Dosiereinheiten.Schluesseltabelle.Dosiereinheit createDosiereinheitenSchluesseltabelleDosiereinheit() {
        return new Dosiereinheiten.Schluesseltabelle.Dosiereinheit();
    }

    /**
     * Create an instance of {@link Dosiereinheiten }
     * 
     */
    public Dosiereinheiten createDosiereinheiten() {
        return new Dosiereinheiten();
    }

}
