//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.20 at 09:24:39 nachm. MESZ 
//


package de.htwg.gib.egkterminal.model.medikationsplan.zwischenueberschrift;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.htwg.gib.egkterminal.model.medikationsplan.zwischenueberschrift package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.htwg.gib.egkterminal.model.medikationsplan.zwischenueberschrift
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Zwischenueberschriften }
     * 
     */
    public Zwischenueberschriften createZwischenueberschriften() {
        return new Zwischenueberschriften();
    }

    /**
     * Create an instance of {@link Zwischenueberschriften.Schluesseltabelle.Zwischenueberschrift }
     * 
     */
    public Zwischenueberschriften.Schluesseltabelle.Zwischenueberschrift createZwischenueberschriftenSchluesseltabelleZwischenueberschrift() {
        return new Zwischenueberschriften.Schluesseltabelle.Zwischenueberschrift();
    }

    /**
     * Create an instance of {@link Zwischenueberschriften.Schluesseltabelle }
     * 
     */
    public Zwischenueberschriften.Schluesseltabelle createZwischenueberschriftenSchluesseltabelle() {
        return new Zwischenueberschriften.Schluesseltabelle();
    }

}
