//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.20 at 08:57:13 nachm. MESZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:ehd/001", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.htwg.gib.egkterminal.model.medikationsplan.darreichungsform;
