//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.10 at 05:16:36 PM MESZ 
//


package de.htwg.gib.egkterminal.model.medikationsplan;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.htwg.gib.egkterminal.model.medikationsplan package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.htwg.gib.egkterminal.model.medikationsplan
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MedikationsPlan }
     * 
     */
    public MedikationsPlan createMedikationsPlan() {
        return new MedikationsPlan();
    }

    /**
     * Create an instance of {@link Ersteller }
     * 
     */
    public Ersteller createErsteller() {
        return new Ersteller();
    }

    /**
     * Create an instance of {@link Rezeptur }
     * 
     */
    public Rezeptur createRezeptur() {
        return new Rezeptur();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link Block }
     * 
     */
    public Block createBlock() {
        return new Block();
    }

    /**
     * Create an instance of {@link Medikation }
     * 
     */
    public Medikation createMedikation() {
        return new Medikation();
    }

    /**
     * Create an instance of {@link Patient }
     * 
     */
    public Patient createPatient() {
        return new Patient();
    }

    /**
     * Create an instance of {@link Freitextzeile }
     * 
     */
    public Freitextzeile createFreitextzeile() {
        return new Freitextzeile();
    }

    /**
     * Create an instance of {@link Wirkstoff }
     * 
     */
    public Wirkstoff createWirkstoff() {
        return new Wirkstoff();
    }

}
