//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.10 at 05:16:36 PM MESZ 
//


package de.htwg.gib.egkterminal.model.medikationsplan;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="w" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;minLength value="1"/>
 *             &lt;maxLength value="80"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="s">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;minLength value="1"/>
 *             &lt;maxLength value="15"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
public class Wirkstoff {

    @XmlAttribute(name = "w", required = true)
    protected String wirkstoff;
    @XmlAttribute(name = "s")
    protected String wirkstaerke;

    /**
     * Gets the value of the wirkstoff property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWirkstoff() {
        return wirkstoff;
    }

    /**
     * Sets the value of the wirkstoff property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWirkstoff(String value) {
        this.wirkstoff = value;
    }

    /**
     * Gets the value of the wirkstaerke property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWirkstaerke() {
        return wirkstaerke;
    }

    /**
     * Sets the value of the wirkstaerke property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWirkstaerke(String value) {
        this.wirkstaerke = value;
    }

}
